# see https://github.com/notFloran/mjml-bundle#binary
mjml:
  renderer: "binary"
  options:
    binary: "%kernel.project_dir%/node_modules/.bin/mjml"
    minify: false

when@prod:
  mjml:
    renderer: 'binary'
    options:
      node: '%env(MJML_NODE)%'
      binary: '%kernel.project_dir%/node_modules/.bin/mjml'
      minify: true
