version: '3.8'

services:
  php:
    extends:
      file: docker-compose.services.yaml
      service: php_81
    networks:
      - default
  back:
    extends:
      file: docker-compose.services.yaml
      service: apache_24_flex
    labels:
      - "traefik.frontend.rule=Host:back.${COMPOSE_PROJECT_NAME}.localhost"
      - "traefik.enable=true"
    networks:
      - traefik
      - default
  front:
    image: hub.iomedia.ch/apache_24_flex
    container_name: ${COMPOSE_PROJECT_NAME}-front
    depends_on:
      - php
    expose:
      - 80 # http port
      - 443 # https port
    volumes:
      - ./:/var/www:rw,cached
    labels:
      - "traefik.frontend.rule=Host:front.${COMPOSE_PROJECT_NAME}.localhost"
      - "traefik.enable=true"
    networks:
      - traefik
      - default
  db:
    extends:
      file: docker-compose.services.yaml
      service: mysql_57
    labels:
      - "traefik.frontend.rule=Host:db.${COMPOSE_PROJECT_NAME}.localhost"
      - "traefik.enable=true"
    networks:
      - traefik
      - default
  mail:
    extends:
      file: docker-compose.services.yaml
      service: mail
    labels:
      - "traefik.frontend.rule=Host:mail.${COMPOSE_PROJECT_NAME}.localhost"
      - "traefik.enable=true"
      - "traefik.port=1080"
    networks:
      - traefik
      - default
  adminer:
    extends:
      file: docker-compose.services.yaml
      service: adminer
    labels:
      - "traefik.frontend.rule=Host:adminer.${COMPOSE_PROJECT_NAME}.localhost"
      - "traefik.enable=true"
      - "traefik.port=8080"
    networks:
      - traefik
      - default

volumes:
  database:

networks:
  traefik:
    external: true
