oneup_flysystem:
  adapters:
    default_adapter:
      local:
        directory: "%kernel.cache_dir%/flysystem"
  filesystems:
    default_filesystem:
      adapter: default_adapter
      alias: League\Flysystem\Filesystem
