services:
  _defaults:
    autowire: true
    autoconfigure: true
  Front\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
